spring:
  redis:
    host: 47.93.239.109
    port: 6379
    password: root
    database: 0
  datasource:
    url: jdbc:mysql://47.93.239.109:3306/oauth?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: oauth
    password: sixtofly
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      # 5分钟
      idle-timeout: 300000
